[package]
name = "aws-config-dump"
description = "Get data from AWS Config"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[lints.clippy]
pedantic = "warn"

[dependencies]
anyhow = "1"
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-config = "1"
aws-smithy-async = "1"
aws-smithy-types-convert = { version = "0.60", features = ["convert-streams"] }
clap = { version = "4", features = ["derive", "wrap_help"] }
clap_complete = { version = "4", features = ["unstable-dynamic"] }
duckdb = "1.4"
futures = "0.3"
serde_json = "1"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
