[package]
name = "aws-config-dump"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[lints.clippy]
pedantic = "warn"

[dependencies]
serde_json = "1"
tokio = { version = "1", features = ["full"] }
